### ISSUE TITLE
System.ArgumentOutOfRangeException: startIndex cannot be larger than length of string.

### ISSUE THREAD

**Issue by mwillems1994** [hishamco/My.Extensions.Localization.Json#63]
In my project i make use of 
`.AddDataAnnotationsLocalization(options =>
{
    options.DataAnnotationLocalizerProvider =
        (type, factory) => factory.Create(type);
});`

Sometimes i get an exception where it tries to do a substring. 

it fails on the following assembly and typeinfo.
* assemblyName = "System.Private.CoreLib"
* typeInfo.FullName = "System.Guid"

It also occures with typeInfo.FullName = "System.string".

I think it occures when i have a url like /user/guid here/profile

A possible 'fix' would be the following:

`
var typeName = $"{assemblyName}.{typeInfo.Name}" == typeInfo.FullName
                ? typeInfo.Name
                : assemblyName?.Length + 1 > typeInfo.FullName?.Length
                    ? typeInfo.Name
                    : typeInfo.FullName.Substring(assemblyName.Length + 1);
`
But i don't know your codebase enough to know the consequences. 

I included the stacktrace

`An unhandled exception has occurred while executing the request.
      System.ArgumentOutOfRangeException: startIndex cannot be larger than length of string. (Parameter 'startIndex')
         at System.String.Substring(Int32 startIndex, Int32 length)
         at System.String.Substring(Int32 startIndex)
         at My.Extensions.Localization.Json.JsonStringLocalizerFactory.Create(Type resourceSource) in /Users/me/Downloads/My.Extensions.Localization.Json-dev/src/My.Extensions.Localization.Json/JsonStringLocalizerFactory.cs:line 57
         at Api.Entreo.Nl.Startup.<>c.<ConfigureServices>b__5_15(Type type, IStringLocalizerFactory factory) in /Users/me/Projects/project/api/Startup.cs:line 110
         at Microsoft.AspNetCore.Mvc.DataAnnotations.DataAnnotationsMetadataProvider.CreateDisplayMetadata(DisplayMetadataProviderContext context)
         at Microsoft.AspNetCore.Mvc.ModelBinding.Metadata.DefaultCompositeMetadataDetailsProvider.CreateDisplayMetadata(DisplayMetadataProviderContext context)
         at Microsoft.AspNetCore.Mvc.ModelBinding.Metadata.DefaultModelMetadata.get_DisplayMetadata()
         at Microsoft.AspNetCore.Mvc.ModelBinding.Metadata.DefaultModelMetadata.get_IsEnum()
         at Microsoft.AspNetCore.Mvc.ModelBinding.Binders.EnumTypeModelBinderProvider.GetBinder(ModelBinderProviderContext context)
         at Microsoft.AspNetCore.Mvc.ModelBinding.ModelBinderFactory.CreateBinderCoreUncached(DefaultModelBinderProviderContext providerContext, Object token)
         at Microsoft.AspNetCore.Mvc.ModelBinding.ModelBinderFactory.CreateBinder(ModelBinderFactoryContext context)
         at Microsoft.AspNetCore.Mvc.Controllers.ControllerBinderDelegateProvider.GetParameterBindingInfo(IModelBinderFactory modelBinderFactory, IModelMetadataProvider modelMetadataProvider, ControllerActionDescriptor actionDescriptor, MvcOptions mvcOptions)`

**Comment by hishamco** [comment]
Thanks for reporting this @mwillems1994, could you please try `LocalizationSample.Mvc` it uses `AddDataAnnotationsLocalization`

**Comment by mwillems1994** [comment]
In your example you pass RegisterViewModel instead of type
`options.DataAnnotationLocalizerProvider = (type, factory) => factory.Create(typeof(RegisterViewModel));`
Therefore it never passes types such as string or guid

**Comment by hishamco** [comment]
> Therefore it never passes types such as string or guid

Could please elaborate? or share a minimal repo, so I can see the bug

**Comment by mwillems1994** [comment]
Thanks for your quick reply.

To reproduce this to the following:

Add this to your startuo
`services.AddControllers()
    .AddDataAnnotationsLocalization(options =>
    {
        options.DataAnnotationLocalizerProvider =
            (type, factory) => factory.Create(type);
    });`
    
Note that i pass type to factory.Create instead of typeof(RegisterViewModel).

No add this controller
`[AllowAnonymous]
public class TestController: ControllerBase
{
    [HttpGet("working")]
    public async Task<string> TestWorkingAsync()
    {
        return "Working";
    }
    
    [HttpGet("{test}/NotWorking")]
    public async Task<string> TestNotWorkingAsync(Guid test)
    {
        return "Not working";
    }
}`

When you request Test/guid here/NotWorking, you get the error.

**Comment by hishamco** [comment]
Thanks for the info, hope to check this ASAP

**Comment by mwillems1994** [comment]
Thanks

**Comment by hishamco** [comment]
One more thing, how the action is related to the DataAnnotation?

**Comment by mwillems1994** [comment]
That is a good question, i think it is because the parameter is passed to the function and therefore it counts as a DataAnnotation.

**Comment by hishamco** [comment]
Hmmm, first time I saw this behavior, I will try to debug this one

**Comment by mwillems1994** [comment]
I took a quick look yesterday and it seems that you use the substring only to make a key in the dictionary. Maybe find an alternative way to build the key.

**Comment by hishamco** [comment]
Feel free to submit a PR if you have a better way

Thanks
